[package]
name = "jobfuscator"
version = "1.1.0"
edition = "2021"
rust-version = "1.70"
license = "Apache-2.0"
description = "JObfuscator is a source code obfuscator for the Java programming language. Obfuscate and protect your Java source code and algorithms from hacking, cracking, reverse engineering, decompilation, and technology theft. JObfuscator provides advanced Java source code parsing based on AST trees, multiple advanced obfuscation strategies are available."
authors = ["Bartosz Wójcik <support@pelock.com>"]
readme = "README.md"
repository = "https://github.com/PELock/JObfuscator-Rust"
homepage = "https://www.pelock.com/products/jobfuscator"
documentation = "https://docs.rs/jobfuscator"
keywords = [
    "java",
    "obfuscator",
    "obfuscation",
    "obfuscate",
    "decompilation"
]
categories = ["api-bindings"]

[dependencies]
base64 = "0.22"
flate2 = "1.0"
reqwest = { version = "0.12", default-features = false, features = [
    "multipart",
    "json",
    "rustls-tls",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["fs", "rt-multi-thread", "macros"] }

[package.metadata.docs.rs]
all-features = true
